services:
  - type: web
    name: learnhub
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn test:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
